//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiscomCFDI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WEBDEV-PC\\SQLEXPRESS;Initial Catalog=siscomsoftCFDI;Integrated Securi" +
            "ty=True")]
        public string siscomsoftCFDIConnectionString {
            get {
                return ((string)(this["siscomsoftCFDIConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=\"C:\\SisCom Pos\\BD\\POS.MDB\"")]
        public string POSConnectionString {
            get {
                return ((string)(this["POSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;User Id=root;password=123;Persist Security Info=True;database=cf" +
            "di")]
        public string cfdiConnectionString {
            get {
                return ((string)(this["cfdiConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.cfdinova.com.mx:59080/axis2/services/TimbradorIntegradores.TimbradorIn" +
            "tegradoresHttpSoap11Endpoint/")]
        public string SiscomCFDI_mx_com_cfdinova_www_TimbradorIntegradores {
            get {
                return ((string)(this["SiscomCFDI_mx_com_cfdinova_www_TimbradorIntegradores"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pruebas.cfdinova.com.mx/axis2/services/TimbradorIntegradores.TimbradorInt" +
            "egradoresHttpsSoap11Endpoint/")]
        public string SiscomCFDI_mx_com_cfdinova_pruebas_TimbradorIntegradores {
            get {
                return ((string)(this["SiscomCFDI_mx_com_cfdinova_pruebas_TimbradorIntegradores"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.tusfacturas.com.mx/axis2/services/TimbradorIntegradores.TimbradorInte" +
            "gradoresHttpsSoap11Endpoint/")]
        public string SiscomCFDI_mx_com_tusfacturas_www_TimbradorIntegradores {
            get {
                return ((string)(this["SiscomCFDI_mx_com_tusfacturas_www_TimbradorIntegradores"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test02.cfdinova.com.mx/axis2/services/TimbradorIntegradores.TimbradorInte" +
            "gradoresHttpsSoap11Endpoint/")]
        public string SiscomCFDI_mx_com_cfdinova_test02_TimbradorIntegradores {
            get {
                return ((string)(this["SiscomCFDI_mx_com_cfdinova_test02_TimbradorIntegradores"]));
            }
        }
    }
}
